// Shared types for the vt-passkey v2 Worker.

export interface Env {
  ACCOUNT: DurableObjectNamespace;
  ASSETS: Fetcher;
  VT_AUTH_CF: string;
  CREDENTIALS_JSON: string;
  PUSHOVER_APP_TOKEN: string;
  PUSHOVER_USER_TOKEN: string;
  WORKER_ORIGIN: string;
  RP_ID: string;
  /** Cloudflare Access team domain, e.g. "myteam.cloudflareaccess.com". Empty → admin surface fails closed. */
  ACCESS_TEAM_DOMAIN: string;
  /** Cloudflare Access Application AUD tag. Empty → admin surface fails closed. */
  ACCESS_AUD: string;
}

// ── Audit (DO SQLite) ──────────────────────────────────────────────────────

/** One row of the DO-internal `audit` table — one row PER CHALLENGE (the
 *  lifecycle stages update this row in place; params are stored once). */
export interface AuditRow {
  id: number;
  token_id: string;
  created_ms: number;
  finalized_ms: number | null;
  status: string;            // pending | approved | rejected | expired
  op_kind: string | null;
  command: string | null;
  reason: string | null;
  host: string | null;
  user: string | null;
  pwd: string | null;
  tty: string | null;
  ppid_cmd: string | null;
  ssh_client: string | null;
  ip: string | null;
  salts: number | null;
  latency_ms: number | null;
  verify_failures: number;
}

export interface AuditQueryResponse {
  rows: AuditRow[];
}

// ── Challenge stored in DO ─────────────────────────────────────────────────

export type ChallengeStatus = 'pending' | 'approved' | 'rejected' | 'expired';

export interface Challenge {
  approve_token: string;
  poll_token: string;
  /** base64url X25519 pubkey from client (32 bytes) */
  daemon_pubkey_b64u: string;
  /** base64url random 16 bytes generated by Worker */
  worker_nonce_b64u: string;
  /** milliseconds epoch, from client body */
  timestamp_ms: number;
  /** base64url SHA-256 commitment for approve flow (see crypto.ts challengeHash, action=approve) */
  approve_challenge_hash_b64u: string;
  /** base64url SHA-256 commitment for reject flow (action=reject) */
  reject_challenge_hash_b64u: string;
  /** per-DEK salts from client, each 16 bytes base64url */
  salts_b64u: string[];
  meta: ChallengeMeta;
  status: ChallengeStatus;
  /** present after approval: sealed_box([DEK_0||...||DEK_n]) to daemon_pubkey */
  sealed_deks_b64u?: string;
  /** present after approval: PWA's ephemeral X25519 public key (32 bytes b64u) */
  pwa_pk_b64u?: string;
  /** present after approval: HMAC-SHA256 tag binding sealed_deks to pwa/daemon ECDH shared secret */
  binding_tag_b64u?: string;
  created_ms: number;
  /** ms epoch when status transitioned to a terminal state (approved/rejected/expired) */
  finalized_ms?: number;
}

export interface ChallengeMeta {
  op_kind: string;
  command: string;
  host: string;
  /** $USER on the daemon machine */
  user: string;
  /** Current working directory of the vt CLI */
  pwd: string;
  /** Controlling TTY (e.g. /dev/pts/3); empty if not a TTY */
  tty: string;
  /** Parent process command line — which shell / script invoked vt */
  ppid_cmd: string;
  /** SSH_CLIENT / SSH_CONNECTION env if the session is remote */
  ssh_client: string;
  ip: string;
  reason: string;
}

// ── Inbound from daemon via POST /api/challenge ────────────────────────────

export interface ChallengeRequest {
  daemon_pubkey_b64u: string;
  timestamp_ms: number;
  /** per-DEK salts; may be empty for auth-only requests */
  salts_b64u: string[];
  meta?: Partial<ChallengeMeta>;
}

// ── Outbound from /api/challenge ───────────────────────────────────────────

export interface ChallengeResponse {
  approve_token: string;
  poll_token: string;
  worker_nonce_b64u: string;
  timestamp_ms: number;
  approve_url: string;
  push_warning?: string;
}

// ── Inbound from PWA via POST /api/approve ─────────────────────────────────

export interface ApproveRequest {
  approve_token: string;
  credential_id_b64u: string;
  /** sealed_box(daemon_pubkey, [DEK_0||...||DEK_n]) from libsodium */
  sealed_deks_b64u: string;
  client_data_json_b64u: string;
  authenticator_data_b64u: string;
  signature_b64u: string;
  /** ephemeral X25519 public key generated by the PWA (32 bytes b64u) */
  pwa_pk_b64u: string;
  /** HMAC-SHA256 tag over the binding transcript (see do_account.ts opApprove) */
  binding_tag_b64u: string;
}

// ── Inbound from PWA via POST /api/reject ─────────────────────────────────

export interface RejectRequest {
  approve_token: string;
  credential_id_b64u: string;
  client_data_json_b64u: string;
  authenticator_data_b64u: string;
  signature_b64u: string;
}

// ── WebSocket message sent to waiting client ──────────────────────────────

export type WsMessage =
  | { status: 'waiting' }
  | { status: 'approved'; sealed_deks_b64u: string; pwa_pk_b64u: string; binding_tag_b64u: string }
  | { status: 'rejected' }
  | { status: 'expired' };

// ── Page data embedded in approve.html ────────────────────────────────────

export interface ApprovePageData {
  approve_token: string;
  approve_challenge_b64u: string;
  reject_challenge_b64u: string;
  daemon_pubkey_b64u: string;
  salts_b64u: string[];
  rp_id: string;
  allow_credentials: Array<{ id_b64u: string; h_b64u: string; k_b64u: string }>;
  metadata: ChallengeMeta;
}

// ── Internal DO op bodies ──────────────────────────────────────────────────

export interface DoCreateOp {
  challenge: Challenge;
}

export interface DoApproveOp {
  approve_token: string;
  credential_id_b64u: string;
  sealed_deks_b64u: string;
  client_data_json_b64u: string;
  authenticator_data_b64u: string;
  signature_b64u: string;
  pwa_pk_b64u: string;
  binding_tag_b64u: string;
}

export interface DoRejectOp {
  approve_token: string;
  credential_id_b64u: string;
  client_data_json_b64u: string;
  authenticator_data_b64u: string;
  signature_b64u: string;
}
